### ISSUE TITLE
http_downlink fails with "Error: failed  to connect"

### ISSUE THREAD

**Issue by senier** [Componolit/componolit#134]
I refactored the HTTP filter demo run file to accept external connections and passing them to lighttpd where our HMI resides. When connection from outside with a web browser (usermode networking redirected to localhost:5555) http_uplink gets the request, (apparently) passes it on to http_downlink which fails to connect to the web server. Output from nic_bridge looks good to me.

```
spawn qemu-system-x86_64 -no-kvm -display sdl -cpu core2duo -net nic,model=e1000 -net user -redir tcp:5555::80 -nographic -serial mon:stdio -m 512 -cdrom var/run/http_filter.iso -machine q35
qemu-system-x86_64: -redir tcp:5555::80: The -redir option is deprecated. Please use '-netdev user,hostfwd=...' instead.
Bender: Hello World.

framebuffer at [b8000+b8fa0) 80x25@16

warning - unknown framebuffer type

framebuffer at [b8000+b8fa0) 80x25@16

warning - unknown framebuffer type

NOVA Microhypervisor v7-9b24eb4 (x86_64): Jun 12 2018 00:15:29 [gcc 6.3.0] [MBI2]

[ 0] TSC:2011989 kHz BUS:1005939 kHz (measured)
[ 0] CORE:0:0:0 6:f:b:0 [0] Intel(R) Core(TM)2 Duo CPU     T7700  @ 2.40GHz
Hypervisor reports 1x1 CPU
Warning: CPU has no invariant TSC.
CPU ID (genode->kernel:package:core:thread) remapping
 remap (0->0:0:0:0) boot cpu
Hypervisor info page contains 12 memory descriptors:
core     image  [0000000000100000,000000000082b000)
binaries region [000000000027a000,000000000082b000) free for reuse
detected physical memory: 0x0000000000000000 - size: 0x000000000009fc00
use      physical memory: 0x0000000000000000 - size: 0x000000000009f000
detected physical memory: 0x0000000000100000 - size: 0x000000001fedf000
use      physical memory: 0x0000000000100000 - size: 0x000000001fedf000
ROM modules:
 ROM: [000000001fc8c000,000000001fcab210) acpi_drv
 ROM: [000000001fa88000,000000001fa89554) config
 ROM: [0000000000016000,0000000000017000) core_log
 ROM: [000000001fd4f000,000000001fd7c8b0) http_downlink
 ROM: [000000001fd17000,000000001fd3bf18) http_uplink
 ROM: [000000001faff000,000000001faff565) index.html
 ROM: [000000001fa8a000,000000001fade380) init
 ROM: [000000001fb52000,000000001fc31b20) ld.lib.so
 ROM: [000000001fd7d000,000000001ff35950) libc.lib.so
 ROM: [000000001ff79000,000000001ffa6fa8) libm.lib.so
 ROM: [000000001fa2d000,000000001fa790d8) lighttpd
 ROM: [000000001fd3c000,000000001fd4e648) log_terminal
 ROM: [000000001ff36000,000000001ff78ac8) lwip.lib.so
 ROM: [000000001ffa7000,000000001ffdd8c8) nic_bridge
 ROM: [000000001fcac000,000000001fd02898) nic_drv
 ROM: [000000001fc56000,000000001fc72270) nic_loopback
 ROM: [000000001fb00000,000000001fb51c58) platform_drv
 ROM: [0000000000014000,0000000000015000) platform_info
 ROM: [000000001fa7a000,000000001fa87d30) posix.lib.so
 ROM: [000000001fadf000,000000001fafe198) report_rom
 ROM: [000000001fd03000,000000001fd16490) test-http_clnt
 ROM: [000000001fc32000,000000001fc552e8) timer
 ROM: [000000001fc73000,000000001fc8b460) zlib.lib.so

Genode 16.11-1991-gb626e4220 <local changes>
467 MiB RAM and 63253 caps assigned to init
[init -> nic_drv] --- iPXE NIC driver started ---
[init -> nic_drv] -- init iPXE NIC
[init -> nic_bridge] --- NIC bridge started (mac=01:02:03:04:05:06) ---
[init -> http_downlink] using the lwIP libc plugin
[init -> acpi_drv] Found MADT
[init -> acpi_drv] MADT IRQ 0 -> GSI 2 flags: 0
[init -> acpi_drv] MADT IRQ 5 -> GSI 5 flags: 13
[init -> acpi_drv] MADT IRQ 9 -> GSI 9 flags: 13
[init -> acpi_drv] MADT IRQ 10 -> GSI 10 flags: 13
[init -> acpi_drv] MADT IRQ 11 -> GSI 11 flags: 13
[init -> acpi_drv] Found MCFG
[init -> acpi_drv] MCFG BASE 0xb0000000 seg 0x0 bus 0x0-0xff
[init -> http_uplink] using the lwIP libc plugin
[init -> http_downlink] init
[init -> http_uplink] init
[init -> http_downlink] Using DHCP for interface configuration.
[init -> platform_drv] ECAM/MMCONF range 00:00.0-ff:1f.7 - addr [00000000b0000000,00000000c0000000)
[init -> http_uplink] Using DHCP for interface configuration.
[init -> lighttpd] using the lwIP libc plugin
[init -> nic_bridge] vmac = 02:02:02:02:02:00 ip = 10.0.2.110
[init -> lighttpd] init
[init -> lighttpd] static network interface: ip_addr=10.0.2.55 netmask=255.255.255.0 gateway=10.0.2.1
[init -> http_downlink] http_downlink
[init -> nic_bridge] vmac = 02:02:02:02:02:01 ip = 10.0.2.55
[init -> lighttpd] 2000-01-01 00:00:00: (/home/alex/Documents/Componolit_GmbH/Devel/src/componolit-master/contrib/lighttpd-33ef60a93420294641033417ab35d36d76372c93/src/app/lighttpd/src/network.c.453) can't set accept-filter 'httpready':  Protocol not
[init -> lighttpd]  available
[init -> lighttpd] Warning: getgid: getgid not implemented
[init -> lighttpd] Warning: getuid: getuid not implemented
[init -> lighttpd] 2000-01-01 00:00:00: (/home/alex/Documents/Componolit_GmbH/Devel/src/componolit-master/contrib/lighttpd-33ef60a93420294641033417ab35d36d76372c93/src/app/lighttpd/src/log.c.194) server started
[init -> nic_drv] Found: 00:02.0 8086:100e (rev 03) IRQ 0b
[init -> nic_drv] using driver 82540em
[init -> nic_drv] PCI BIOS has not enabled device 00:02.0! Updating PCI command 0103->0107
[init -> nic_drv]
[ 0] sys_assign_pci: Invalid Hint (0x10)
[init -> platform_drv] Error: nic_drv -> : assignment of PCI device 0:2.0 failed phys=0xb0010000 virt=0x1000
[init -> nic_drv] PCI device 00:02.0 latency timer is unreasonably low at 0. Setting to 32.
[init -> nic_drv]
[init -> nic_drv] bus_addr = febc0000 len = 20000
[init -> nic_drv] snprintf not implemented
[init -> platform_drv] IRQ override 11->11, trigger mode: LEVEL, polarity: HIGH
[init -> platform_drv] 00:02.0 uses IRQ, vector 0xb, non-maskable
[init -> nic_drv] MAC address 52:54:00:12:34:56
[init -> http_uplink] http_uplink
[init -> http_uplink] got IP address 10.0.2.15
[init -> http_uplink] Connection from: 10.0.2.2:39276
[init -> http_downlink] pthread_main_np_int: pthread_main_np called, not implemented
[init -> http_downlink] pthread_main_np_int: pthread_main_np called, not implemented
[init -> http_downlink] Warning: rtc not configured, returning 0
[init -> http_downlink] pthread_main_np_int: pthread_main_np called, not implemented
[init -> http_downlink] Error: Failed to connect
Expect: 'interact' received 'strg+c' and was cancelled
```

**Comment by jklmnn** [comment]
I can't reproduce the issue since lighttpd doesn't seem to find the website (I checked that bin/index.html is available, it is also available in NOVAs rom pages)
```
[init -> lighttpd] Error: ROM-session creation failed (ram_quota=6144, cap_quota=3, label="")
[init -> lighttpd] Error: Could not open ROM session for ""
[init -> lighttpd] Error: failed to create <rom> VFS node
```

**Comment by jklmnn** [comment]
The downlink component is not getting a DHCP IP address. Uplink gets one at
```
[init -> http_uplink] http_uplink
[init -> http_uplink] got IP address 10.0.2.15
```
but this part is missing for the downlink. Since it has no IP it obviously cannot connect. But I cannot find a valid reason why this doesn't work.

Also you maybe want to cherry-pick https://github.com/jklmnn/componolit/commit/21a7ff4d45548f9381f2c28b850e6a7e1ec27c84 which configures the uplink with a static ip address so it keeps working if another component actually uses DHCP and the addresses are changeing between components.

**Comment by senier** [comment]
TBH, I don't understand the setup. The `http_downlink` component provides the Terminal session and uses a Nic session. This suggests it needs to connect to bridge where lighttpd is connected to. `http_uplink` is the component using terminal sessions and the external NIC, hence its Nic session must be routed to the real `nic_drv`. You patch suggests it's the other way round. Am I missing something here?

**Comment by jklmnn** [comment]
I failed to see that the uplink isn't connected to the `nic_bridge` anymore so my patch is of course unnecessary.
The downlink should be connected to the bridge and get an ip address via dhcp which doesn't seem to work. Yet using a static address worked for me. https://github.com/jklmnn/componolit/commit/d8663bdf762624bb7c3862c85bdedb895a7f1aed (without the patch from my previous comment) should fix the issue.

**Comment by jklmnn** [comment]
Can you show me the full log? There should be something like
```
[init -> http_downlink] static network interface: ip_addr=10.0.2.110 netmask=255.255.255.0 gateway=10.0.2.1
```
somewhere.

And yes I get the website. I only noticed that the connection closing does not seem to work correctly. The browser is waiting for the server until I stop the process and then shows the website (also somehow broken but script.js and style.css are not available to the lighttpd).

**Comment by jklmnn** [comment]
Okay, more specifically not the connection closing is the problem but opening a second one after the first has been closed seems to hang.

**Comment by senier** [comment]
Funny, I'm at precisely at the same point with my JWX sample proxy in Ada/Linux. In the browser you  always have at least 2 requests: the page and favicon.ICO.

**Comment by senier** [comment]
I can now replicated the behavior you are describing. As a reference, the commit I'm talking about is https://github.com/Componolit/componolit/commit/4ba4b7f7f2bdab24543ad821b83c3b175d3c0340.

The main page gets retrieved but not displayed immediately, the subsequent requests are issued: `script.js`, `style.css` and `favicon.iso`. Instead of a 404 (they are actually still missing from the demo), no response is sent. As soon as I interrupt the Qemu process, the TCP connections get closed and the browser continues (assume an empty response for the above requests).

**Comment by jklmnn** [comment]
The problem consists of two things:
 - the connection teardown was incomplete which resulted in a "socket leak" leaving open sockets
 - of all the sockets opened the first one that has been opened and is still open will get data so the recv calls of all others won't return.

Since the first socket stays open due to the socket leak the second will block indefinitely on the first call on read and no further connection can be made. This is fixed by https://github.com/jklmnn/componolit/commit/c89ca32f4dd88e99104ec137b6cccc14ab8c31f3.

Yet for the second problem I don't have a solution yet. This behaviour prevents concurrent connections from working.

**Comment by jklmnn** [comment]
I think I know why this doesn't work. As long as connection 1 is open, it has its read thread in a blocking call of recv which also blocks all other recv operations of other libc sockets. The solution would be to create a component-global thread that registers a socket for each connection, calls select and signals the the according connection to be ready when select returns (if needs to keep track of connection-socket-relations ofc).

**Comment by senier** [comment]
I can confirm that you above fix works. When setting the maximum parallel connection per server to 1 in Firefox (`network.http.max-persistent-connections-per-server`), then the page shows immediately (as requests get serialized).

I don't fully understand why problem 2 happens. If you think the global thread does the trick, please try it.

**Comment by jklmnn** [comment]
After implementing the libc read on the tcp client i get into the same problems with parallel connections. I tried the lighttpd directly and it seems to support it. I'll build a simple tcp echo server to simplify the problem.

**Comment by jklmnn** [comment]
https://github.com/jklmnn/componolit/commit/e438cbd06493bab7c77bec652371e85a9012c5da provides a simple tcp echo server that also can handle multiple simoultaneous connections.

**Comment by jklmnn** [comment]
I have implemented the read part with polling without a separate thread now. Currently I poll with 100ms, you can choose between cpu load and latency by modifying this value.
I tried a non-polling approach but I wasn't able to create any solution that blocks and waits and is canceable if the connection is closed. At some point there was either a page fault or an endlessly blocking libc call.
The current approach is implemented in https://github.com/jklmnn/componolit/commit/c49d65e5c25e0d20ee50348a8b6297593ac82a92. Is has the advantage that there are no blocking libc calls which keeps the flow control code at Genode.

You can try this with https://github.com/jklmnn/componolit/commit/d3da1ac615e1a47322f14faa51cdc243f38b7759. Currently loading the page works even with multiple simultaneous connections. Yet sometimes there is still some kind of block somewhere inbetween the request.  I suspect this could have something to do with the connection keep alive that firefox is using. Using the reload button sometimes fails to complete all requests but closing the tab and opening it again works.

**Comment by senier** [comment]
This fails for me with Chrome and `ab` (Apache benchmark tool). Seems like `http_filter` hangs after the first response. Consecutive invocations of `wget` work. Firefox sometimes works (with concurrent connections forced to `1`). Firefox hangs with concurrent connections set to 6.

**Comment by jklmnn** [comment]
From your edit I assume that it should work without the filter. Is this the case?

**Comment by senier** [comment]
No, removing the filter does not change anything. `ab` kills the setup reliably. Without the keepalive feature this happens immediately:

```
$ ab -n 1000 http://127.0.0.1:5555/demo.html                                                                                                                                        
This is ApacheBench, Version 2.3 <$Revision: 1757674 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)
apr_pollset_poll: The timeout specified has expired (70007)
```

With the keepalive feature enabled (-k) it reliably dies after 16 requests, with the last message going form `http_downlink` to `nic_bridge` (according to `nic_dump`):

```
$ ab -n 1000 -k http://127.0.0.1:5555/demo.html
This is ApacheBench, Version 2.3 <$Revision: 1757674 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)
apr_pollset_poll: The timeout specified has expired (70007)
Total of 16 requests completed
```

Could `nic_bridge` be our problem?

**Comment by senier** [comment]
We can rule out `nic_dump` as the culprit for this particular issue. Same behavior when removing it.

**Comment by jklmnn** [comment]
I'm not sure how feasible this is and how fast this could be done. But maybe we can try to use lxip and connect the terminal_s_tcp_c via vfs to the lighttpd (although I haven't used vfs yet).

**Comment by senier** [comment]
Connecting it without any intermediate component? I doubt this works - we probably will still need something like `nic_router`. I'm currently trying to integrate it into our scenario in favor of `nic_bridge`.

**Comment by senier** [comment]
I integrated `nic_bridge` (cf. https://github.com/Componolit/componolit/commit/e3c8f4afa15123d8512cb3f43c69ab4c1a93f349). Observations:

1. It works
2. It has nicer debug output than `nic_dump`
3. There seems to be an issue with `nic_dump` which prevents DHCP from working - removing it caused DHCP to succeed (with `nic_router` being the DHCP server)
4. That does not solve our problem ;-( `ab` reliably causes the error after 16 packets.

The last message of `nic_bridge` is interesting (its running under name `hub`):

```
[init -> hub] Dissolve TCP link: CLN src 10.0.3.1:49153 dst 10.0.4.1:80 SRV src 10.0.4.1:80 dst 10.0.3.1:49153
```
10.0.4.1 is our lighttpd server. 10.0.3.1 is the address of `terminal_tcp`.

**Comment by jklmnn** [comment]
I still have the assumption that there is a problem with connection closing. The whole time I had problems encoding the relevant information into the terminal session. From the Terminal client side this isn't that much of a problem since the client can explicitly end the connection by destructing the object. Yet the server can't end the session by itself (afaik) so it has to send some kind of signal to the client which is a problem. Without adding further signals (and therefore forking the actual Terminal session into another one) the only communication methods are read availability (manually or by signal) and the return values of read and write. Setting these to 0 would be logical but this also can happen in other circumstances. I tried this but either it stays quite fragile and connections get closed if no data is available from the beginning or some connections never close as read gets never called again and since the client doesn't write anymore write also doesn't get called. The way this connection closed is at some time when the client times out but this isn't particularly reliable. Another way would be to set the return values to -1 (or 2**32/2**64, b/c unsigned) which isn't really nice but could work since we most probably never reach these values due to obvious buffer size constraints.

Aside from that I think we maybe should further reduce our test setup and test these components in a single environment (as far as this is doable).

What also could be interesting would be a http server that doesn't use tcp/ip at all but instead stdio which we could attach to the terminal session more directly. Yet I'm not sure id a usable and portable server exist or if implementing our own server (with just GET / and some headers) would be feasible.

**Comment by senier** [comment]
I agree that smaller tests would be good to track down the issue.

As for writing a custom web server: While possible, this would defeat our main advantage, being able to simply drop in a validation component and reusing everything else.

Different idea: how about we only use a single Terminal section which never gets closed. We'd then need meta data on that channel to separate connections. Would make the verifier more complex, BUT if we wrap data into JSON objects that additional complexity could be moderate.

**Comment by jklmnn** [comment]
Using a single terminal connection and adding meta data would most probably solve many of the current issues and would be probably a less complex approach. Yet I'm unsure if JSON is a good choice here. While this would be quite flexible I think it is overengineered to what we intend to do. I'd prefer a simple (text or binary) header that includes a connection id and status (do we need anything more than that). Closing the connection would be a packet with only the header and a "close" (or whatever) status.

**Comment by senier** [comment]
Normally I would agree (or maybe not, as I've seen too many "simple" homemade protocols to cause massive trouble and debugging overhead). For this instance, I think we should indeed use JSON. The reasoning is, that the complexity of the untrusted components like the TCP/Terminal converters does not matter from a security point of view. We can use an existing library. For the trusted filter, we get the JSON serialization for free, as we need it anyway to handle JWTs. Building a custom protocol - no matter how simple - would increase complexity.

**Comment by jklmnn** [comment]
As discussed lwip seems to be somewhat broken so I will change everything to lxip (although I have to wait for an answer from the mailing list first as I have no idea how to use it properly; the `lxip_udp_echo` example seems promising but I can't spot the differences why this works and my component throws errors).

**Comment by senier** [comment]
Cf. #138
